'use client';
import { useEffect, useState } from 'react';
import { api } from './api-client';
export type AppUser = {id: string; name: string; email: string; role: 'admin' | 'editor' | 'viewer'; active?: number};
export function Login({onLogin}: {onLogin: () => Promise<void>}) {
  const [email,setEmail]=useState(''), [password,setPassword]=useState(''), [error,setError]=useState(''), [busy,setBusy]=useState(false);
  return <main className="auth-screen"><form className="panel auth-card" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('auth/login','POST',{email,password});await onLogin();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><span className="eyebrow">Gestão de Subvenção</span><h1>Acesse sua conta</h1><p>Entre para acompanhar os projetos da organização.</p><label className="field"><span>E-mail</span><input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field"><span>Senha</span><input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary-button full" disabled={busy}>{busy?'Entrando…':'Entrar'}</button></form></main>;
}
export function AccountPanel({user,onClose,onLogout}: {user:AppUser;onClose:()=>void;onLogout:()=>void}) {
  const [users,setUsers]=useState<AppUser[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const reload=async()=>{if(user.role==='admin')setUsers(await api('users'));};
  useEffect(()=>{reload().catch(e=>setError(e.message));},[]);
  const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="modal-backdrop"><section className="modal large" role="dialog" aria-modal="true" aria-label="Conta e acessos"><div className="modal-header"><h2>Conta e acessos</h2><button onClick={onClose} className="secondary-button">Fechar</button></div><div className="modal-body"><p>{user.name} · {user.email}</p><p>Os usuários autorizados têm acesso aos projetos desta organização. A equipe técnica do projeto não recebe acesso automaticamente.</p>{error&&<p role="alert" className="form-error">{error}</p>}{message&&<p role="status">{message}</p>}{user.role==='admin'&&<><h3>Usuários da organização</h3>{users.map(u=><div className="account-user" key={u.id}><span>{u.name} · {u.email} · {u.role}</span>{u.id!==user.id&&<button disabled={busy} className="secondary-button small" onClick={()=>action(async()=>{await api('users/'+u.id,'PATCH',{active:!u.active});await reload();})}>{u.active?'Desativar':'Reativar'}</button>}</div>)}<form className="form-grid account-form" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;const fields=new FormData(f);void action(async()=>{await api('users','POST',Object.fromEntries(fields));f.reset();await reload();setMessage('Usuário criado. Compartilhe a senha inicial por um canal privado.');});}}><h3 className="full">Adicionar usuário</h3><label className="field"><span>Nome</span><input name="name" required/></label><label className="field"><span>E-mail</span><input name="email" type="email" required/></label><label className="field"><span>Senha inicial</span><input name="password" type="password" minLength={12} maxLength={256} autoComplete="new-password" required/></label><label className="field"><span>Permissão</span><select name="role"><option value="editor">Editar registros</option><option value="viewer">Somente consulta</option><option value="admin">Administrar</option></select></label><button disabled={busy} className="primary-button">Criar usuário</button></form></>}<form className="form-grid account-form" onSubmit={e=>{e.preventDefault();const fields=new FormData(e.currentTarget);void action(async()=>{await api('auth/password','POST',Object.fromEntries(fields));onLogout();});}}><h3 className="full">Alterar minha senha</h3><label className="field"><span>Senha atual</span><input name="currentPassword" type="password" autoComplete="current-password" required/></label><label className="field"><span>Nova senha</span><input name="password" type="password" minLength={12} maxLength={256} autoComplete="new-password" required/></label><button disabled={busy} className="secondary-button">Salvar nova senha</button></form></div><div className="modal-footer"><button className="secondary-button" disabled={busy} onClick={()=>action(async()=>{await api('auth/logout','POST',{});onLogout();})}>Sair da conta</button></div></section></div>;
}
