import { sourceOf, resourceSource } from '../lib/funding.mjs';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = value => Number(value || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const sum = rows => rows.reduce((s,r)=>s+Math.round(r.value*100),0)/100;
function table(headers, rows) {
  return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">Nenhum registro.</td></tr>`}</tbody></table></div>`;
}
export function renderReport(r) {
  const p=r.project,expenses=r.expenses.filter(e=>!e.draft),drafts=r.expenses.filter(e=>e.draft);
  const pending=expenses.filter(e=>e.docs<e.requiredDocs);
  const sourceRows=['Subvenção','Contrapartida'].map(source=>{
    const incoming=r.resources.filter(x=>resourceSource(x)===source),spent=expenses.filter(x=>sourceOf(x)===source);
    const planned=r.planning.filter(x=>x.source===source).reduce((s,x)=>s+Math.round(x.planned*100),0)/100;
    const limit=source==='Subvenção'?p.approved:p.counterpart;
    return [source,money(limit),money(planned),money(sum(incoming)),money(sum(spent)),money((Math.round(sum(incoming)*100)-Math.round(sum(spent)*100))/100),limit?`${(sum(spent)/limit*100).toFixed(1)}%`:'—'];
  });
  const movements=[...r.reconciliation.incoming.map(x=>({...x,label:x.kind,amount:x.value})),...r.reconciliation.outgoing.map(x=>({...x,label:x.description,amount:-x.value,reference:x.bankReference||'Sem conferência'}))].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
  let balance=0;
  const bankRows=movements.map(x=>{balance+=Math.round(x.amount*100);return [x.date,x.label,x.reference,money(x.amount),money(balance/100)];});
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Relatório — ${esc(p.name)}</title><style>
  @font-face{font-family:Geist;src:url('/fonts/Geist-latin.woff2')}*{box-sizing:border-box}body{font-family:Geist,Arial,sans-serif;color:#172b36;background:#f3f6f8;margin:0;font-size:14px;line-height:1.5}main{max-width:1280px;margin:32px auto;background:white;padding:40px;border-radius:16px}header{border-bottom:3px solid #167569;margin-bottom:28px;padding-bottom:20px}h1{font-size:30px;margin:8px 0}h2{font-size:20px;margin:32px 0 12px}p{margin:8px 0}small,.muted{color:#566774}.eyebrow{color:#167569;font-weight:700;text-transform:uppercase;letter-spacing:.1em}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{background:#eef6f4;padding:18px;border-radius:10px}.card strong{display:block;font-size:25px}.table-wrap{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:12px}th{background:#edf3f6;text-align:left}td,th{padding:10px;border-bottom:1px solid #dce5ea;vertical-align:top;overflow-wrap:anywhere}tr{break-inside:avoid}thead{display:table-header-group}h2{break-after:avoid}button{background:#13695f;color:white;border:0;padding:12px 18px;border-radius:8px;cursor:pointer;font:inherit}.actions{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:25px}.notice{background:#fff5df;padding:15px;border-radius:8px}@media print{@page{size:A4 landscape;margin:12mm}body{background:white;font-size:11px}main{margin:0;padding:0;max-width:none}.actions{display:none}.table-wrap{overflow:visible}table{font-size:9px}td,th{padding:6px}h1{font-size:24px}h2{font-size:16px}.card strong{font-size:20px}footer{margin-top:20px}}
  </style></head><body><main><div class="actions"><span>Relatório gerencial completo</span><button onclick="window.print()">Imprimir / Salvar em PDF</button></div><header><span class="eyebrow">Gestão de recursos do projeto</span><h1>${esc(p.name)}</h1><p>${esc(p.code)} · ${esc(p.agency)} · ${esc(p.startDate)} a ${esc(p.endDate)}</p><p>${esc(r.company.name)} · CNPJ ${esc(r.company.cnpj)} · ${esc(r.company.city)}/${esc(r.company.state)}</p><small>Responsável: ${esc(r.company.responsible)} · ${esc(r.company.email)}<br>Emitido em ${esc(new Date(r.generatedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}))} (Brasília)</small></header>
  <section class="summary"><div class="card">Executado — subvenção<strong>${money(p.executedSubvention)}</strong></div><div class="card">Executado — contrapartida<strong>${money(p.executedCounterpart)}</strong></div><div class="card">Saldo da conta de subvenção<strong>${money(r.reconciliation.balance)}</strong></div></section>
  <h2>1. Resumo financeiro por fonte</h2>${table(['Fonte','Previsto no projeto','Planejado','Entradas registradas','Executado','Saldo calculado','Execução'],sourceRows)}<p class="muted">As entradas de subvenção incluem rendimentos de ${money(p.income)}. Os saldos são calculados pelos registros da plataforma. Rascunhos não entram no executado.</p>
  <h2>2. Planejamento e execução por rubrica</h2>${table(['Fonte','Rubrica','Planejado','Executado','Disponível'],r.planning.map(x=>[x.source,x.rubric,money(x.planned),money(x.executed),money((Math.round(x.planned*100)-Math.round(x.executed*100))/100)]))}
  <h2>3. Recursos e parcelas recebidos</h2>${table(['Data','Fonte','Tipo','Parcela','Referência','Valor','Comprovantes'],r.resources.map(x=>[x.date,resourceSource(x),x.kind,x.installment||'—',x.reference,money(x.value),x.documents.map(d=>d.name).join('; ')||'Pendente']))}
  <h2>4. Lançamentos e documentos</h2><p>${expenses.length} despesas registradas · ${drafts.length} rascunhos · ${pending.length} despesas com documentos pendentes.</p>${table(['Data','Fonte','Rubrica','Fornecedor','Descrição','Valor','Situação','Documentos'],r.expenses.map(x=>[x.date,sourceOf(x),x.rubric,x.supplier,x.description,money(x.value),x.draft?'Rascunho':x.status,`${x.docs}/${x.requiredDocs} · ${x.documents.map(d=>d.name).join('; ')||'Sem anexos'}`]))}
  ${pending.length?`<p class="notice">Documentos a completar: ${esc(pending.map(x=>`${x.supplier} (${x.missingDocuments.join(', ')})`).join('; '))}.</p>`:''}
  <h2>5. Conciliação da conta de subvenção</h2>${table(['Data','Movimentação','Referência','Entrada / saída','Saldo acumulado'],bankRows)}<p class="muted">Somente entradas e despesas da subvenção. A conferência com o extrato é manual.</p>
  <h2>6. Cronograma de execução</h2>${table(['Fonte','Rubrica','Atividade','Mês / ano','Valor previsto','Status'],r.schedule.map(x=>[sourceOf(x),x.rubric||x.item,x.activity,`${x.month}/${x.year||'—'}`,money(x.value),x.status]))}
  <h2>7. Remanejamentos</h2>${table(['Data','Fonte','Origem','Destino','Atividade','Valor','Justificativa','Situação'],r.remaps.map(x=>[x.date,sourceOf(x),x.from,x.to,x.activity,money(x.value),x.reason,x.status==='Aprovado'?'Aplicado':'Registro anterior pendente']))}
  <h2>8. Equipe técnica</h2>${table(['Nome','Função','Atividade'],r.team.map(x=>[x.name,x.role,x.activity]))}
  <h2>9. Links e referências</h2>${table(['Nome','Endereço','Data'],r.links.map(x=>[x.name,x.url,x.addedAt]))}
  <footer class="muted">Relatório gerencial baseado nos dados cadastrados. Os comprovantes originais podem ser baixados na plataforma.</footer></main></body></html>`;
}
